inspirehep/inspire-json-merger

- README.rst
- inspire_json_merger/comparators.py
- inspire_json_merger/version.py
- setup.cfg
- setup.py
Signed-off-by: Riccardo Candido <riccardo.candido@gmail.com>
> boilerplate for pypi

- inspire_json_merger/comparators.py
- inspire_json_merger/merger_config.py
- setup.py
- tests/fixtures/arxiv2arxiv/expected_merged.json
- tests/unit/test_merger_arxiv2arxiv.py
* Introduced schema validation at the end of each unit test
* added inspire-schema to setup.py requirements
* changed assertion in according to the latest schema
* fixed comparator for `titles` field
> tests: introduced schema validation in unit tests

- inspire_json_merger/comparators.py
Signed-off-by: Javier Martin Montull <javier.martin.montull@cern.ch>
> AuthorComparator threshold fix

- setup.py
- tests/unit/test_merger_arxiv2arxiv.py
* added a decorator to each test to collect the schema's key under test
* check the schema's keys covered by the test itself
> tests: check schema keys coverage

- .gitignore
- inspire_json_merger/inspire_json_merger.py
- inspire_json_merger/merger_config.py
- inspire_json_merger/utils/utils.py
- setup.py
- tests/conftest.py
- tests/integration/test_json_merger.py
- tests/unit/test_merger_arxiv2arxiv.py
- tests/utils/utils.py
Signed-off-by: Antonio Cesarano <cesarano2607@gmail.com>
> global: bump to inspire-schemas v50.0 and json-merger v0.3.1

- setup.py
- tests/unit/test_merger_arxiv2arxiv.py
Signed-off-by: Micha Moskovic <michamos@gmail.com>
> setup: bump inspire-schemas to version ~53.0

- setup.py
Signed-off-by: Micha Moskovic <michamos@gmail.com>
> setup: bump inspire-schemas to version ~56.0

- .travis.yml
- requirements.txt
- tests/unit/test_api.py
Signed-off-by: Micha Moskovic <michamos@gmail.com>
> tests: demonstrate dictdiffer bug

- inspire_json_merger/comparators.py
- inspire_json_merger/config.py
- tests/unit/test_merger_arxiv2arxiv.py
Signed-off-by: David Caro <david@dcaro.es>
> figures: keep the update on matching key

- setup.py
Signed-off-by: Harris Tzovanakis <me@drjova.com>
Sem-Ver: breaks compatibility
> setup: bump the version

- inspire_json_merger/config.py
- run-tests.sh
- setup.py
- tests/unit/test_merger_arxiv2arxiv.py
This reverts commit 7919293b590a680206cf3dfba866cae7e5875a8c.
Signed-off-by: Antonio Cesarano <cesarano2607@gmail.com>
> Revert a685b23 global: not raise conflict when head adds an author - INSPIR-1122"

- setup.py
sem-ver: breaks compatibility
Signed-off-by: Victor Balbuena <vbalbp@gmail.com>
> bump inspire schemas and utils version

- inspire_json_merger/pre_filters.py
- setup.py
- tests/unit/test_pre_filters.py
Prompted by https://rt.inspirehep.net/Ticket/Display.html?id=893953 and https://labs.inspirehep.net/holdingpen/inspect/1289792.
> pre_filters: ignore minor diffs for ref comparison

- inspire_json_merger/pre_filters.py
- tests/unit/test_pre_filters.py
Signed-off-by: Harris Tzovanakis <me@drjova.com>
> pre_filters: fix curated ref comparison

- inspire_json_merger/config.py
- tests/unit/test_merger.py
Fixes issue when merging ArxivOnPublisher and it was returning empty document list
> Fixed empty documents in merged record when merging ArxivOnPublisher

- setup.py
- tests/unit/test_api.py
- tests/unit/test_filterout_utils.py
Signed-off-by: Micha Moskovic <michamos@gmail.com>
Sem-Ver: breaks compatibility
> setup: bump inspire-schemas to v60.*

- .gitignore
- inspire_json_merger/api.py
- inspire_json_merger/config.py
- inspire_json_merger/postprocess.py
- inspire_json_merger/pre_filters.py
- inspire_json_merger/utils.py
- tests/unit/test_api.py
> api:for authors replace MANUAL_MERGE with simpler replace

- inspire_json_merger/config.py
- tests/unit/test_api.py
- tests/unit/test_merger.py
- tests/unit/test_merger_arxiv2arxiv.py
ref: inspirehep/inspirehep#1155
> change default behaviour to keep head on conflict

- inspire_json_merger/postprocess.py
- tests/unit/test_merger_arxiv2arxiv.py
- tests/unit/test_postprocess.py
ref: inspirehep/inspirehep#1154
> replace ADD_BACK_TO_HEAD with opposite behaviour

- inspire_json_merger/comparators.py
- inspire_json_merger/config.py
- inspire_json_merger/pre_filters.py
- tests/unit/test_merger.py
> Comparators: Use TitleComparator on titles and ignore conflicts on title.source

- inspire_json_merger/comparators.py
- inspire_json_merger/config.py
- inspire_json_merger/pre_filters.py
- tests/unit/test_merger_arxiv2arxiv.py
Ref: inspirehep/inspirehep#1719
> arxivonarxiv: change merging rules

- inspire_json_merger/pre_filters.py
- tests/unit/test_merger.py
- tests/unit/test_pre_filters.py
> pre_filters: update 'remove_duplicated_titles' to not expect 'source' to be in titles.

- inspire_json_merger/api.py
- inspire_json_merger/comparators.py
- inspire_json_merger/config.py
- tests/unit/test_api.py
ref: inspirehep/inspirehep#1816
> config: add new config for comparing arxiv and grobid authors

- inspire_json_merger/api.py
- inspire_json_merger/config.py
- inspire_json_merger/pre_filters.py
- tests/unit/test_api.py
- tests/unit/test_pre_filters.py
* ref inspirehep/inspirehep#1345
> Simplify manual merge

- inspire_json_merger/config.py
- tests/unit/test_merger.py
ref: inspirehep/inspirehep#1874
> config: always keep update in acquisition_source

- inspire_json_merger/config.py
- inspire_json_merger/pre_filters.py
- tests/unit/test_merger.py
- tests/unit/test_pre_filters.py
ref: inspirehep/inspirehep#1977
> acquisition_source: always use update for source

- inspire_json_merger/api.py
- inspire_json_merger/comparators.py
- inspire_json_merger/config.py
- inspire_json_merger/pre_filters.py
- setup.py
- tests/unit/test_api.py
- tests/unit/test_merger.py
- tests/unit/test_merger_arxiv2arxiv.py
- tests/unit/test_pre_filters.py
ref:inspirehep/inspirehep#2292
> handle errata

- inspire_json_merger/api.py
- tests/unit/test_api.py
Ref: https://github.com/cern-sis/issues-inspire/issues/12
> add publisher correction to erratum keywords

- inspire_json_merger/postprocess.py
- setup.py
* Fix import issues duo to changes in collection package starting with Python 3.10
> update actions for py311

- setup.py
* ref https://github.com/cern-sis/issues-inspire/issues/837
> setup: bump json merger

- inspire_json_merger/api.py
- tests/unit/test_api.py
ref: https://github.com/cern-sis/issues-inspire/issues/861
> erraturm: add author correction keyword

- .github/workflows/bump-and-publish.yml
ref: https://github.com/cern-sis/issues-inspire/issues/1029
> actions: fix package build
